# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullanici_bilgi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(754, 457)
        Form.setStyleSheet("    background-color: #363636;\n"
"")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 591, 391))
        self.groupBox_2.setStyleSheet("background-color: rgb(97, 97, 97);\n"
"color: black;\n"
"\n"
"\n"
"")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(130, 20, 321, 221))
        self.groupBox.setStyleSheet("color: black;")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.label_kullanici_foto = QtWidgets.QLabel(self.groupBox)
        self.label_kullanici_foto.setGeometry(QtCore.QRect(60, 40, 161, 151))
        self.label_kullanici_foto.setText("")
        self.label_kullanici_foto.setObjectName("label_kullanici_foto")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(300, 40, 20, 151))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_kullanici_adi = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_kullanici_adi.setGeometry(QtCore.QRect(160, 290, 281, 51))
        self.lineEdit_kullanici_adi.setStyleSheet("background-color: #CCCCCC;\n"
"")
        self.lineEdit_kullanici_adi.setObjectName("lineEdit_kullanici_adi")
        self.pushButton_kullanici_bilgi_kaydet = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_kullanici_bilgi_kaydet.setGeometry(QtCore.QRect(470, 350, 93, 28))
        self.pushButton_kullanici_bilgi_kaydet.setStyleSheet("background-color: #3EA6FF;\n"
"")
        self.pushButton_kullanici_bilgi_kaydet.setObjectName("pushButton_kullanici_bilgi_kaydet")
        self.pushButton_resim_sec = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_resim_sec.setGeometry(QtCore.QRect(250, 240, 93, 28))
        self.pushButton_resim_sec.setStyleSheet("background-color: #3EA6FF;\n"
"")
        self.pushButton_resim_sec.setObjectName("pushButton_resim_sec")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(140, 269, 321, 21))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setGeometry(QtCore.QRect(140, 60, 20, 151))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "BİLGİLERİNİ GÜNCELLE"))
        self.groupBox.setTitle(_translate("Form", "PROFİL RESMİ"))
        self.lineEdit_kullanici_adi.setPlaceholderText(_translate("Form", "KULLANICI ADI"))
        self.pushButton_kullanici_bilgi_kaydet.setText(_translate("Form", "KAYDET"))
        self.pushButton_resim_sec.setText(_translate("Form", "resim seç"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
